# Generated by Django 3.1.2 on 2020-10-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201014_1759'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scanneditem',
            table='ScannedItem',
        ),
    ]
