# Generated by Django 3.1.2 on 2020-11-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201102_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='Item',
        ),
        migrations.RemoveField(
            model_name='scanneditem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='scanneditem',
            name='scan',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NI', 'Not Initiated'), ('FL', 'Failed'), ('PD', 'Paid')], default='NI', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ST', 'Started'), ('FL', 'Failed'), ('FN', 'Finished')], default='ST', max_length=2),
        ),
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='ScannedItem',
        ),
    ]
