# Generated by Django 3.1.2 on 2020-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201102_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
